// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6woJzfVXfyYxu8FVi8HwDWlB6VAgaxNo',
    appId: '1:693511293330:web:0177ecb6c0f3115c32194b',
    messagingSenderId: '693511293330',
    projectId: 'iotroshark',
    authDomain: 'iotroshark.firebaseapp.com',
    databaseURL: 'https://iotroshark-default-rtdb.firebaseio.com',
    storageBucket: 'iotroshark.firebasestorage.app',
    measurementId: 'G-6PZFL7R1C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-j7xpYtcGU9hDsLX8ii1-yrBD8YtUk8',
    appId: '1:693511293330:android:0b3406883ce5ca6932194b',
    messagingSenderId: '693511293330',
    projectId: 'iotroshark',
    databaseURL: 'https://iotroshark-default-rtdb.firebaseio.com',
    storageBucket: 'iotroshark.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6woJzfVXfyYxu8FVi8HwDWlB6VAgaxNo',
    appId: '1:693511293330:web:135f6b2bb0a3c05432194b',
    messagingSenderId: '693511293330',
    projectId: 'iotroshark',
    authDomain: 'iotroshark.firebaseapp.com',
    databaseURL: 'https://iotroshark-default-rtdb.firebaseio.com',
    storageBucket: 'iotroshark.firebasestorage.app',
    measurementId: 'G-WL0FW4NBCE',
  );
}
